### ISSUE TITLE
How to autoRemove observer for KVO?

### ISSUE THREAD

**Issue by howmacist** [intuit/AutoRemoveObserver#2]
Hello, is you removing KVO oberserver removal meaning it is impossiple to auto remove observer for KVO? 
If there is a way ? It would be very helpful to  give me some keywords.

**Comment by gilroykilroy** [comment]
The issue we were originally trying to address was when the item being observed went away the observation stopped as well and didn't leave a dangling reference. Apple changed it recently to automatically remove the observers when the object goes away so negating the need for this class anymore.

**Comment by howmacist** [comment]
@gilroykilroy Really? I was working with a demo, it seems that Apple is not autoremoving the observers. 
```
2017-01-08 22:30:35.141 WR[1222:43307] *** Terminating app due to uncaught 
exception 'NSInternalInconsistencyException', 
reason: 'An instance 0x79210a00 of class WKWebView was deallocated
 while key value observers were still registered with it. 
Current observation info: <NSKeyValueObservationInfo 0x7863c300> (
<NSKeyValueObservance 0x786b5860: Observer: 0x78703e20,
 Key path: estimatedProgress,
 Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x786b5840>
)'
```
